//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_KQXN
    {
        public string Ma_CT_KQXN { get; set; }
        public string MaKQ { get; set; }
        public string Loai_XN { get; set; }
        public Nullable<double> Glucose { get; set; }
        public Nullable<double> Urê { get; set; }
        public Nullable<double> Creatinin { get; set; }
        public Nullable<double> Cholesterol { get; set; }
        public Nullable<double> Triglycerid { get; set; }
        public Nullable<double> HDL_Cholesterol { get; set; }
        public Nullable<double> AST_GOT { get; set; }
        public Nullable<double> ALT_GPT { get; set; }
        public Nullable<double> GGT { get; set; }
        public Nullable<double> Acid_Uric { get; set; }
    }
}
