//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV
{
    using System;
    using System.Collections.Generic;
    
    public partial class KQXN
    {
        public string MaKQ { get; set; }
        public string MaBN { get; set; }
        public string Khoa { get; set; }
        public string Chuan_Doan { get; set; }
        public Nullable<System.DateTime> TG_NM { get; set; }
        public string BS_ChiDinh { get; set; }
        public string Loai_XN { get; set; }
    }
}
