//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_BenhNhan
    {
        public string MaBN { get; set; }
        public string Ten_BN { get; set; }
        public string Gioi_Tinh { get; set; }
        public string Dia_Chi { get; set; }
        public Nullable<System.DateTime> Ngay_Sinh { get; set; }
        public string So_BHYT { get; set; }
        public string Loai_DV_Kham { get; set; }
    }
}
